/**
 * Reads `.env` (repo root) and writes `src/environments/secrets.generated.ts`.
 * Existing `process.env` values are preserved (so CI can inject vars without a file).
 * Run: npm run env:sync  (also runs via prestart / prebuild / postinstall)
 */
const fs = require("fs");
const path = require("path");

const rootDir = path.join(__dirname, "..");
const examplePath = path.join(rootDir, ".env.example");
const envPath = path.join(rootDir, ".env");

// Defaults from `.env.example`, then real values from `.env` (override: true so `.env` wins).
// Variables already set in the shell (e.g. CI) are left untouched by dotenv until `.env` overrides.
if (fs.existsSync(examplePath)) {
  require("dotenv").config({ path: examplePath });
}
if (fs.existsSync(envPath)) {
  require("dotenv").config({ path: envPath, override: true });
}

function tsString(value) {
  if (value === undefined || value === null) return '""';
  return JSON.stringify(String(value));
}

const outPath = path.join(rootDir, "src", "environments", "secrets.generated.ts");

const env = process.env;
const geminiModel =
  env.GEMINI_MODEL && String(env.GEMINI_MODEL).trim()
    ? String(env.GEMINI_MODEL).trim()
    : "gemini-2.0-flash";

const lines = [
  "/**",
  " * AUTO-GENERATED by scripts/sync-env.cjs — do not edit by hand.",
  " * Source: `.env` at repo root (gitignored). Template: `.env.example`.",
  " * Regenerate: npm run env:sync",
  " */",
  "",
  `export const GEMINI_API_KEY = ${tsString(env.GEMINI_API_KEY)};`,
  `export const GEMINI_MODEL = ${tsString(geminiModel)};`,
  "",
  `export const FIREBASE_API_KEY = ${tsString(env.FIREBASE_API_KEY)};`,
  `export const FIREBASE_AUTH_DOMAIN = ${tsString(env.FIREBASE_AUTH_DOMAIN)};`,
  `export const FIREBASE_PROJECT_ID = ${tsString(env.FIREBASE_PROJECT_ID)};`,
  `export const FIREBASE_STORAGE_BUCKET = ${tsString(env.FIREBASE_STORAGE_BUCKET)};`,
  `export const FIREBASE_MESSAGING_SENDER_ID = ${tsString(env.FIREBASE_MESSAGING_SENDER_ID)};`,
  `export const FIREBASE_APP_ID = ${tsString(env.FIREBASE_APP_ID)};`,
  `export const FIREBASE_MEASUREMENT_ID = ${tsString(env.FIREBASE_MEASUREMENT_ID)};`,
  "",
];

fs.writeFileSync(outPath, lines.join("\n"), "utf8");

const hasEnvFile = fs.existsSync(envPath);
if (!hasEnvFile) {
  console.warn(
    "[env] No `.env` file found. Copy `.env.example` → `.env` and fill in values. Using empty / process defaults for secrets.generated.ts.",
  );
} else {
  console.log("[env] Wrote src/environments/secrets.generated.ts from .env");
}
